trigger:
  - master

pool: 'Default'

variables:
  imageRepository: 'test-repository'
  dockerfilePath: 'Dockerfile'
  azureContainerRegistryServiceConnection: MyACRServiceConnection
  azureServiceConnection: MyAzureServiceConnection
  containerAppName: 'test-repository'
  resourceGroup: 'test-rg-1'
  acrName: 'testacrdev1'
  tag: $(Build.BuildNumber)
  imageName: test-repository
  group: container-app-secrets

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build job
        steps:
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(azureContainerRegistryServiceConnection)
              tags: |
                $(tag)

  - stage: Deploy
    jobs:
      - job: DeployJob
        variables:
         - group: container-app-secrets
        steps:
          - task: AzureContainerApps@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              imageToDeploy: 'testacrdev1.azurecr.io/test-repository:$(tag)'
              containerAppName: 'test-repository'
              resourceGroup: $(resourceGroup)
              containerAppEnvironment: 'development'
              location: 'westeurope'
              targetPort: 8080
              ingress: 'external'
              acrName: 'testacrdev1'
              acrUsername: 'testacrdev1'
              acrPassword: $(acrPassword)